plugins {
    id 'com.android.application'
}

android {
    namespace 'com.weng.weng'
    compileSdk 34

    defaultConfig {
        applicationId "com.weng.weng"
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName "1.5"
    }

    signingConfigs {
        weng {
            storeFile file('keystore.p12')
            storePassword 'wengweng123'
            keyAlias 'wengwengwu'
            keyPassword 'wengweng123'
            storeType 'PKCS12'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.weng
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.weng
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
